### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by SravanKumarjampani** [benetis/benetis.me#3]
I'm trying to execute your shopping cart application but i'm getting error please help to resolve the bugs..

ERROR in src/app/services/products.service.ts:14:8 - error TS2339: Property 'map' does not exist on type 'Observable<Product[]>'.

14       .map(_ => {
          ~~~
src/app/services/cart.service.ts:29:36 - error TS2339: Property 'map' does not exist on type 'BehaviorSubject<Product[]>'.       

29     return this.itemsInCartSubject.map((items: Product[]) => {
                                      ~~~

ERROR in Unexpected value 'CartService in D:/Proj/src/app/services/cart.service.ts' imported by the module 'AppModule in D:/Proj/src/app/app.module.ts'. Please add a @NgModule annotation.
Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.

![Capture](https://user-images.githubusercontent.com/28763217/76504590-06b61d80-646e-11ea-9710-0ea5b2c5f9a0.PNG)

**Comment by benetis** [comment]
Blog was written with quite the old angular version. Check it out, it should work
